# Generated by Django 4.2.13 on 2024-05-25 17:23

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_locations'),
    ]

    operations = [
        migrations.AddField(
            model_name='locations',
            name='address',
            field=models.CharField(blank=True, max_length=245),
        ),
        migrations.AddField(
            model_name='locations',
            name='location_url',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='locations',
            name='location',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, geography=True, null=True, srid=4326),
        ),
    ]
