# Generated by Django 4.2.13 on 2024-05-25 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='carservice',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='car_image/'),
        ),
    ]
