# Generated by Django 4.2.13 on 2024-05-25 17:23

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_carservice_day_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotelservice',
            name='day_price',
            field=models.DecimalField(decimal_places=2, default=None, max_digits=10),
            preserve_default=False,
        ),
    ]
