# Generated by Django 4.2.13 on 2024-05-25 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0004_hotelservice_day_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='carservice',
            name='points_day_price',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='durationoption',
            name='points_price',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hotelservice',
            name='points_day_price',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
