# Generated by Django 4.2.13 on 2024-05-25 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0005_carservice_points_day_price_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='HotelServiceFeatures',
            new_name='HotelServiceFeature',
        ),
        migrations.RenameField(
            model_name='carservice',
            old_name='day_price',
            new_name='price',
        ),
        migrations.RemoveField(
            model_name='carservice',
            name='points_day_price',
        ),
        migrations.RemoveField(
            model_name='durationoption',
            name='points_price',
        ),
        migrations.RemoveField(
            model_name='hotelservice',
            name='points_day_price',
        ),
        migrations.AlterField(
            model_name='carimage',
            name='image',
            field=models.FileField(upload_to='car_images/'),
        ),
    ]
