# Generated by Django 4.2.13 on 2024-05-25 17:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0002_alter_payment_payment_method'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carreservationoption',
            name='final_price',
        ),
        migrations.RemoveField(
            model_name='hotelreservationoption',
            name='final_price',
        ),
    ]
