# Generated by Django 4.2.13 on 2024-05-25 20:07

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0004_carreservation_dropoff_adress_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentGateWay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
                ('transaction_id', models.CharField(blank=True, max_length=100, null=True)),
                ('payment_date', models.DateTimeField(blank=True, null=True)),
                ('response', models.JSONField()),
                ('call_back', models.JSONField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RefundGateWay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
                ('transaction_id', models.CharField(blank=True, max_length=100, null=True)),
                ('response', models.JSONField()),
                ('call_back', models.JSONField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='refund',
            name='reservation',
        ),
        migrations.RenameField(
            model_name='carreservation',
            old_name='dropoff_adress',
            new_name='dropoff_address',
        ),
        migrations.RenameField(
            model_name='carreservation',
            old_name='pickup_adress',
            new_name='pickup_address',
        ),
        migrations.RenameField(
            model_name='hotelreservation',
            old_name='adress',
            new_name='address',
        ),
        migrations.AddField(
            model_name='reservation',
            name='payment_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reservation',
            name='payment_method',
            field=models.CharField(choices=[('CREDIT_CARD', 'Credit Card'), ('WALLET', 'Wallet'), ('CASH_ON_DELIVERY', 'Cash on Delivery'), ('CAR_POS', 'Car Point of Sale'), ('POINTS', 'Points')], default='WALLET', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reservation',
            name='payment_status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], default='PENDING', max_length=20),
        ),
        migrations.AddField(
            model_name='reservation',
            name='refund_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='reservation',
            name='refund_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reservation',
            name='refund_method',
            field=models.CharField(blank=True, choices=[('CREDIT_CARD', 'Credit Card'), ('WALLET', 'Wallet')], max_length=20, null=True),
        ),
        migrations.DeleteModel(
            name='Payment',
        ),
        migrations.DeleteModel(
            name='Refund',
        ),
        migrations.AddField(
            model_name='refundgateway',
            name='reservation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='refund', to='reservations.reservation'),
        ),
        migrations.AddField(
            model_name='paymentgateway',
            name='reservation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment', to='reservations.reservation'),
        ),
    ]
